{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "a566d380-5a25-4ec2-b7f2-52f38f7b1d5a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Financial Analysis\n",
      "----------------------------\n",
      "Total Months:  86\n",
      "Total: $ 38382578\n",
      "Average Change: $ 539138.05\n",
      "Greatest Increase in Profits:  Feb-2012 $ 1926159\n",
      "Greatest Decrease in Profits:  Sep-2013 $ -2196167\n"
     ]
    }
   ],
   "source": [
    "month_num = 0\n",
    "pl_total = 0\n",
    "pl_subtotal = 0\n",
    "monthly_diff = int\n",
    "monthly_diff_total = 0\n",
    "diff_spot = 0\n",
    "g_profit = 0\n",
    "g_loss = 0\n",
    "avg_change = 0\n",
    "\n",
    "import csv\n",
    "with open('budget_data.csv', 'r') as infile:\n",
    "    reader = csv.reader(infile, delimiter = \",\")\n",
    "    header = next(reader)\n",
    "\n",
    "   \n",
    "    record_max = []\n",
    "    record_min = []\n",
    "    diff_lag = 0\n",
    "    for row in reader:\n",
    "        pl_subtotal = int(row[1])\n",
    "        diff_spot = int(row[1])\n",
    "         \n",
    "        pl_total += pl_subtotal\n",
    "        monthly_diff = diff_spot - diff_lag\n",
    "        if monthly_diff == diff_spot:\n",
    "            monthly_diff = 0\n",
    "        monthly_diff_total += daily_diff\n",
    "        \n",
    "        diff_lag = diff_spot\n",
    "        \n",
    "        month_num += 1\n",
    "\n",
    "           \n",
    "        if g_loss == 0:\n",
    "            g_loss = monthly_diff\n",
    "            record_min = row\n",
    "        elif monthly_diff < g_loss:\n",
    "            g_loss = monthly_diff\n",
    "            record_min = row\n",
    "        elif monthly_diff > g_profit:\n",
    "            g_profit = monthly_diff\n",
    "            record_max = row\n",
    "\n",
    "        \n",
    "avg_change = round(monthly_diff_total / (month_num - 1), 2)\n",
    "\n",
    "#header.append(\"Daily_Diff\")\n",
    "#records.append(reader)\n",
    "\n",
    "#for record in reader:\n",
    "    #writer.writerow(record)    \n",
    "\n",
    "\n",
    "        \n",
    "\n",
    "\n",
    "print(\"Financial Analysis\")\n",
    "print(\"----------------------------\")\n",
    "print(f\"Total Months: \", month_num)\n",
    "print(f\"Total: $\", pl_total)\n",
    "print(f\"Average Change: $\",avg_change)\n",
    "print(f\"Greatest Increase in Profits: \", record_max[0],\"$\",g_profit)\n",
    "print(f\"Greatest Decrease in Profits: \", record_min[0],\"$\",g_loss)\n",
    "\n",
    "#Your final script should print the analysis to the terminal and export a text file with the results.\n",
    "\n",
    "f = open(\"Financial Analysis Output.txt\", \"w\")\n",
    "f.write (\"Financial Analysis\")\n",
    "f.write (\"\\n________________________________\")\n",
    "f.write (\"\\nTotal Months: \" + str(month_num))\n",
    "f.write (\"\\nTotal Profit & Loss: $\" + str(pl_total))\n",
    "f.write (\"\\nAverage P&L change: $\" + str(avg_change))\n",
    "f.write (\"\\nGreatest Increase in Profits: \" + str(record_max[0])+ \" $ \" + str(g_profit))\n",
    "f.write (\"\\nGreatest loss on record: \" + str(record_min[0]) + \" $ \" + str(g_loss))\n",
    "f.close()\n",
    "\n",
    "f_out=open (\"Financial Analysis Output.txt\", \"r\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7ca39f9e-47b7-4ca6-aa9a-b4b03da1e05f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "61dff614-b501-4c3a-abd6-8edf2eca6123",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
